version: "3.7"
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
      # - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306
    networks:
      - demo_network
    security_opt:
      - seccomp:unconfined
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - demo_network
    depends_on:
      - db

  demo:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 8005:8005
    networks:
      - demo_network
    depends_on:
      - db

networks:
  demo_network: null
